stages:
  - test
  - quality-control
  - build
  - publish
  - performances
  - review
  - deploy

variables:
  DOCKER_TLS_CERTDIR: ""
  CI_IMAGE_VERSION: $CI_COMMIT_SHORT_SHA
  MAVEN_CLI_OPTS: "--show-version -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Ddocker-registry-image=${CI_REGISTRY_IMAGE} -Ddocker-registry-host-push=${CI_REGISTRY} -Ddocker-registry-host-pull=${CI_REGISTRY_PULL} -Ddocker-registry-group=${CI_REGISTRY_NAMESPACE}"
  NODE_CLUSTER_IP: "192.168.88.120"
  DOCKER_REGCRED: "nexus-regcred"
  ## TODO change it, use common name you like!!!
  CI_REGISTRY_IMAGE: "springboot-example"
  CI_REGISTRY_NAMESPACE: "examples/k8s-gitlab-cicd"

cache:
  paths:
    - .m2/repository

image: $CI_REGISTRY_PULL/maven:3.6.3-jdk-11

include:
  - local: /.gitlab/jobs/testing.gitlab-ci.yaml
  - local: /.gitlab/jobs/packaging.gitlab-ci.yaml

#docker-publish:
#  stage: publish
#  services:
#    - name: $CI_REGISTRY_PULL/docker:18.09-dind
#      # Enabled insecure registry into docker inside docker
#      entrypoint: [ "dockerd-entrypoint.sh" ]
#      # TODO changed variable `--insecure-registry`
#      command: [
#          "--insecure-registry=repository.dimas-maryanto.com:8087",
#          "--insecure-registry=repository.dimas-maryanto.com:8086"
#      ]
#      alias: dockerd
#  variables:
#    # modified file /etc/hosts inside docker container
#    DOCKER_HOST: tcp://dockerd:2375
#    DOCKER_DRIVER: overlay2
#  script:
#    - mvn -s $M2_SETTINGS_XML versions:set -DnewVersion=$CI_IMAGE_VERSION
#    - mvn -s $M2_SETTINGS_XML $MAVEN_CLI_OPTS -DskipTests package dockerfile:build dockerfile:push
#  only:
#    - /-release/
#  tags:
#    - docker
#
#review_apps:
#  image:
#    name: dimmaryanto93/k8s-kubectl-helm:1.21.1-release
#  stage: review
#  tags:
#    - docker
#  environment:
#    name: review/$CI_COMMIT_REF_SLUG
#    on_stop: stop_review_apps
#    url: http://NODE_CLUSTER_IP:$NODE_PORT
#    auto_stop_in: 1 week
#  before_script:
#    - kubectl config set-context --current --namespace="$KUBE_NAMESPACE"
#    - sh .gitlab/runners/entrypoint.sh
#    - sh .gitlab/runners/regcred-entrypoint.sh
#  script:
#    - kubectl apply -f .k8s/deployment.yaml -n $KUBE_NAMESPACE
#    - kubectl apply -f .k8s/service.yaml -n $KUBE_NAMESPACE
#  after_script:
#    - NODE_PORT_ENV=$(kubectl get service $CI_PROJECT_PATH_SLUG -n $KUBE_NAMESPACE -o=jsonpath='{.spec.ports[?(@.port==8080)].nodePort}')
#    - echo "NODE_PORT=$NODE_PORT_ENV" >> deploy.env
#  artifacts:
#    reports:
#      dotenv: deploy.env
#    paths:
#      - .k8s/
#    name: $CI_PROJECT_NAME-$CI_COMMIT_TAG
#  only:
#    - /-release/
#
#stop_review_apps:
#  image:
#    name: dimmaryanto93/k8s-kubectl-helm:1.21.1-release
#  stage: review
#  tags:
#    - docker
#  environment:
#    name: review/$CI_COMMIT_REF_SLUG
#    action: stop
#  when: manual
#  before_script:
#    - kubectl config set-context --current --namespace="$KUBE_NAMESPACE"
#    - sh .gitlab/runners/entrypoint.sh
#  script:
#    - kubectl delete -f .k8s/deployment.yaml -n $KUBE_NAMESPACE
#    - kubectl delete -f .k8s/service.yaml -n $KUBE_NAMESPACE
#  only:
#    - /-release/
