stages:
  - test
  - quality-control
  - build
  - publish
  - performances
  - review
  - deploy

variables:
  DOCKER_TLS_CERTDIR: ""
  CI_IMAGE_VERSION: $CI_COMMIT_SHORT_SHA
  MAVEN_CLI_OPTS: "--show-version -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Ddocker-registry-image=${CI_REGISTRY_IMAGE} -Ddocker-registry-host-push=${CI_REGISTRY} -Ddocker-registry-host-pull=${CI_REGISTRY_PULL} -Ddocker-registry-group=${CI_REGISTRY_NAMESPACE}"
  DOCKER_REGCRED: "nexus-regcred"
  CI_REGISTRY_IMAGE: $CI_PROJECT_NAME
  CI_REGISTRY_NAMESPACE: $CI_PROJECT_NAMESPACE
  ### TODO change this value then inside job folder for `after_script` to get service port at `NODE_PORT_ENV=$(kubectl get service .... -o=jsonpath='{.spec.ports[?(@.port==8080)].nodePort}` if you need custome expose port 
  CI_IMAGE_EXPOSE_PORT: 8080
  NODE_CLUSTER_IP: "192.168.88.120"

cache:
  paths:
    - .m2/repository

image: $CI_REGISTRY_PULL/maven:3.6.3-jdk-11

include:
  - local: .gitlab/jobs/testing.gitlab-ci.yaml
  - local: .gitlab/jobs/packaging.gitlab-ci.yaml
  - local: .gitlab/jobs/publish.gitlab-ci.yaml
  - local: .gitlab/jobs/review.gitlab-ci.yaml # required `publish.gitlab-ci.yaml`
  - local: .gitlab/jobs/deploy.gitlab-ci.yaml # required `publish.gitlab-ci.yaml`
