docker_storage_driver: overlay2
docker_insecure_registries_enabled: true
docker_insecure_registries_conf:
  - url: "192.168.100.250:8088"
    auth:
      docker_login: true      
      user: tabeldata
      password: tabeldata