---
apiVersion: v1
kind: Service
metadata:
  name: ${CI_PROJECT_PATH_SLUG}
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: ${CI_PROJECT_PATH_SLUG}
  selector:
    app: ${CI_PROJECT_PATH_SLUG}
    env: ${CI_ENVIRONMENT_SLUG}
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-postgres-example
spec:
  ports:
    - port: 5432
      targetPort: 5432
      name: ${CI_PROJECT_PATH_SLUG}-${CI_ENVIRONMENT_SLUG}-db
  selector:
    app: ${CI_PROJECT_PATH_SLUG}
    env: ${CI_ENVIRONMENT_SLUG}
  type: ClusterIP
