---
apiVersion: v1
kind: Service
metadata:
  name: ${CI_PROJECT_PATH_SLUG}
spec:
  ports:
    - port: ${CI_IMAGE_EXPOSE_PORT}
      targetPort: ${CI_IMAGE_EXPOSE_PORT}
      name: ${CI_PROJECT_PATH_SLUG}
      nodePort: ${CI_NODE_PORT_EXPOSE}
  selector:
    app: ${CI_PROJECT_PATH_SLUG}
    env: ${CI_ENVIRONMENT_SLUG}
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: ${CI_PROJECT_PATH_SLUG}-db
spec:
  ports:
    - port: 5432
      targetPort: 5432
      name: ${CI_PROJECT_PATH_SLUG}-db
  selector:
    app: ${CI_PROJECT_PATH_SLUG}-db
    env: ${CI_ENVIRONMENT_SLUG}-db
  type: ClusterIP
