building:
  stage: build
  before_script:
    - mvn -s $M2_SETTINGS_XML versions:set -DnewVersion=$CI_IMAGE_VERSION
  script:
    - mvn -s $M2_SETTINGS_XML $MAVEN_CLI_OPTS package -DskipTests
  only:
    - /-release/
  tags:
    - docker
  artifacts:
    paths:
      - target/*.jar
    name: $CI_PROJECT_NAME-$CI_COMMIT_TAG
